[package]
name = "helper-discord"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
helper-core = { path = "../helper-core" }
helper-contracts = { path = "../helper-contracts" }
helper-modules = { path = "../helper-modules" }
helper-store = { path = "../helper-store" }
serenity.workspace = true
tokio.workspace = true
tracing.workspace = true
