import { useEffect, useMemo, useState } from 'react';
import { api, type AuditRecord, type CaseRecord, type Feature, type FeatureConfig, type Guild, type Me, type RankCardConfig } from './api';

const defaultRankCard: RankCardConfig = { font: 'system', primary_color: '#8EE5D2', text_color: '#F4F7FB', background_color: '#101725', overlay_opacity: 0.36, background_preset: null, background_url: null, background_data: null, avatar_ring_color: '#8EE5D2', avatar_ring_width: 4 };
const swatches = ['#8EE5D2', '#7F9CF5', '#F6AD55', '#F687B3', '#A78BFA', '#F4F7FB'];
const presetOptions = [['aurora-lake', 'Aurora Lake', './rank-card-banners/banner-01-aurora-lake.png'], ['neon-rain', 'Neon Rain', './rank-card-banners/banner-02-neon-rain.png'], ['enchanted-forest', 'Enchanted Forest', './rank-card-banners/banner-03-enchanted-forest.png'], ['desert-ruins', 'Desert Ruins', './rank-card-banners/banner-04-desert-ruins.png'], ['coral-cavern', 'Coral Cavern', './rank-card-banners/banner-05-coral-cavern.png'], ['sky-islands', 'Sky Islands', './rank-card-banners/banner-06-sky-islands.png'], ['volcanic-forge', 'Volcanic Forge', './rank-card-banners/banner-07-volcanic-forge.png'], ['moonlit-village', 'Moonlit Village', './rank-card-banners/banner-08-moonlit-village.png'], ['starship-hangar', 'Starship Hangar', './rank-card-banners/banner-09-starship-hangar.png'], ['lavender-storm', 'Lavender Storm', './rank-card-banners/banner-10-lavender-storm.png']] as const;
const localPreviewMode = !(import.meta.env.VITE_HELPER_API_BASE as string | undefined);

type Category = 'all' | 'protection' | 'community' | 'management';
type Route = { page: 'overview' | 'features' | 'activity' | 'rank-card' | 'detail'; key?: string };
type FieldSpec = { key: string; label: string; kind: 'toggle' | 'text' | 'number' | 'select' | 'textarea' | 'tags'; help?: string; options?: [string, string][]; min?: number; max?: number; maxLength?: number; step?: number; advanced?: boolean };
type SectionSpec = { title: string; description: string; fields: FieldSpec[] };

const pages = [{ id: 'overview', label: 'Painel', icon: '⌂', hint: 'Visão geral' }, { id: 'features', label: 'Funcionalidades', icon: '✦', hint: 'Configurar módulos' }, { id: 'activity', label: 'Atividade', icon: '◷', hint: 'Histórico do servidor' }, { id: 'rank-card', label: 'XP card', icon: '▣', hint: 'Níveis e identidade' }] as const;
const categories: { id: Category; label: string }[] = [{ id: 'all', label: 'Todas' }, { id: 'protection', label: 'Proteção' }, { id: 'community', label: 'Comunidade' }, { id: 'management', label: 'Gestão' }];
const demoGuilds: Guild[] = [{ id: 'demo', name: 'Servidor de demonstração', canManage: true }];
const demoFeatures: Feature[] = [
  { key: 'protection.antispam', label: 'Anti-spam', description: 'Reduz mensagens repetidas e comportamento de flood.', category: 'protection', capability: 'security', available: true, enabled: true },
  { key: 'protection.antiscam', label: 'Anti-scam', description: 'Deteta ligações e padrões comuns de fraude.', category: 'protection', capability: 'security', available: true, enabled: true },
  { key: 'protection.anti_raid', label: 'Anti-raid', description: 'Responde a entradas anormais e protege o servidor.', category: 'protection', capability: 'security', available: true, enabled: false },
  { key: 'protection.join_gate', label: 'Proteção de entradas', description: 'Aplica verificações básicas a novos membros.', category: 'protection', capability: 'security', available: true, enabled: false },
  { key: 'community.levels', label: 'Níveis e XP', description: 'Recompensa conversa saudável com XP e níveis.', category: 'community', capability: 'community', available: true, enabled: false },
  { key: 'community.starboard', label: 'Starboard', description: 'Destaca mensagens populares da comunidade.', category: 'community', capability: 'community', available: true, enabled: false },
  { key: 'community.suggestions', label: 'Sugestões', description: 'Recolhe ideias e deixa a comunidade votar.', category: 'community', capability: 'community', available: true, enabled: false },
  { key: 'community.giveaways', label: 'Giveaways', description: 'Cria sorteios com entradas rastreáveis.', category: 'community', capability: 'events', available: true, enabled: false },
  { key: 'support.tickets', label: 'Tickets', description: 'Organiza pedidos de suporte num só lugar.', category: 'management', capability: 'support', available: true, enabled: false },
  { key: 'support.welcome', label: 'Boas-vindas', description: 'Recebe novos membros com uma mensagem guiada.', category: 'management', capability: 'core', available: true, enabled: false },
  { key: 'management.nickname', label: 'Nickname', description: 'Define o nome que o Helper mostra neste servidor.', category: 'management', capability: 'core', available: true, enabled: false },
  { key: 'management.workflows', label: 'Automações', description: 'Liga um gatilho a uma resposta sem código.', category: 'management', capability: 'automate', available: true, enabled: false },
  { key: 'management.polls', label: 'Enquetes', description: 'Publica votações simples para decisões rápidas.', category: 'management', capability: 'events', available: true, enabled: false },
  { key: 'insights.stats', label: 'Canais de estatísticas', description: 'Acompanha atividade e tendências do servidor.', category: 'management', capability: 'insights', available: true, enabled: false },
  { key: 'studio.rank_card', label: 'XP card', description: 'Personaliza a carta de nível mostrada no Discord.', category: 'community', capability: 'studio', available: true, enabled: true },
];
const defaults: Record<string, FeatureConfig> = {
  'protection.antispam': { sensitivity: 'balanced', floodCount: 6, duplicateLimit: 3, timeoutSeconds: 60, mentionLimit: 5, ignoredChannels: [], ignoredRoles: [], logChannel: '', alertOnly: false },
  'protection.antiscam': { enabledLinks: true, blockedDomains: [], protectedDomains: [], action: 'delete_timeout', timeoutMinutes: 10, ignoreTrustedRoles: true, logChannel: '' },
  'protection.anti_raid': { joinThreshold: 8, windowSeconds: 20, incidentMinutes: 10, verification: 'high', pauseInvites: true, alertOnly: false, alertChannel: '' },
  'protection.join_gate': { minimumAccountDays: 7, requireAvatar: false, blockedNamePatterns: [], action: 'quarantine', verifiedRole: '', autoRole: '', logChannel: '' },
  'community.levels': { xpMin: 15, xpMax: 30, cooldownSeconds: 60, ignoredChannels: [], announceChannel: '', announceTemplate: '{member} chegou ao nível {level}!', stackRoles: true, levelRoles: [] },
  'community.starboard': { emoji: '⭐', threshold: 5, channel: '', allowSelfStar: false, ignoredChannels: [], includeImages: true },
  'community.suggestions': { channel: '', anonymous: false, voteMode: 'up_down', cooldownHours: 24, requiredRole: '', staffChannel: '' },
  'community.giveaways': { defaultDurationHours: 24, defaultWinners: 1, requiredRole: '', bonusRole: '', rerollHours: 48 },
  'support.tickets': { category: '', staffRoles: [], transcriptChannel: '', maxOpen: 1, closeAfterHours: 72, panelTitle: 'Precisas de ajuda?', panelDescription: 'Abre um ticket e a nossa equipa responde em breve.' },
  'support.welcome': { channel: '', message: 'Bem-vindo(a), {member}! Lê as regras e diverte-te.', sendDm: false, dmMessage: 'Olá {member}, bem-vindo(a) ao servidor!', autoRole: '', delaySeconds: 0 },
  'management.nickname': { nickname: '' },
  'management.workflows': { defaultAction: 'send_message', logChannel: '', dryRun: true, workflows: [] },
  'management.polls': { defaultDurationHours: 24, allowMultiple: false, anonymous: false, reminderHours: 6, channel: '' },
  'insights.stats': { channel: '', refreshMinutes: 15, showMembers: true, showMessages: true, showVoice: true },
};

const spec = (key: string): SectionSpec[] => {
  const map: Record<string, SectionSpec[]> = {
    'protection.antispam': [{ title: 'Resposta automática', description: 'Ajusta a sensibilidade sem precisares de conhecer os limites internos.', fields: [{ key: 'sensitivity', label: 'Perfil de proteção', kind: 'select', options: [['relaxed', 'Relaxado'], ['balanced', 'Equilibrado'], ['strict', 'Rigoroso']], help: 'Equilibrado é recomendado para começar.' }, { key: 'floodCount', label: 'Mensagens no intervalo', kind: 'number', min: 3, max: 30 }, { key: 'duplicateLimit', label: 'Repetições iguais', kind: 'number', min: 2, max: 12 }, { key: 'timeoutSeconds', label: 'Timeout inicial (segundos)', kind: 'number', min: 0, max: 86400 }] }, { title: 'Exceções e alertas', description: 'Evita falsos positivos e escolhe onde a equipa recebe contexto.', fields: [{ key: 'mentionLimit', label: 'Limite de menções por mensagem', kind: 'number', min: 1, max: 30, advanced: true }, { key: 'ignoredChannels', label: 'Canais ignorados', kind: 'tags', help: 'IDs ou nomes separados por vírgula.', advanced: true }, { key: 'ignoredRoles', label: 'Cargos ignorados', kind: 'tags', advanced: true }, { key: 'logChannel', label: 'Canal de registo', kind: 'text', advanced: true }, { key: 'alertOnly', label: 'Apenas alertar, sem aplicar castigo', kind: 'toggle', advanced: true }] }],
    'protection.antiscam': [{ title: 'Deteção de fraude', description: 'Controla como o Helper reage a links e domínios suspeitos.', fields: [{ key: 'enabledLinks', label: 'Verificar links e convites', kind: 'toggle' }, { key: 'action', label: 'Ação aplicada', kind: 'select', options: [['delete', 'Apagar mensagem'], ['delete_timeout', 'Apagar e aplicar timeout'], ['quarantine', 'Enviar para quarentena']] }, { key: 'timeoutMinutes', label: 'Timeout (minutos)', kind: 'number', min: 1, max: 10080 }] }, { title: 'Listas de confiança', description: 'Uma lista protegida reduz falsos positivos em links legítimos.', fields: [{ key: 'blockedDomains', label: 'Domínios bloqueados', kind: 'tags', advanced: true }, { key: 'protectedDomains', label: 'Domínios protegidos', kind: 'tags', advanced: true }, { key: 'ignoreTrustedRoles', label: 'Ignorar cargos de confiança', kind: 'toggle', advanced: true }, { key: 'logChannel', label: 'Canal de registo', kind: 'text', advanced: true }] }],
    'protection.anti_raid': [{ title: 'Deteção de entradas', description: 'Define quando uma sequência de entradas passa a ser considerada raid.', fields: [{ key: 'joinThreshold', label: 'Entradas para iniciar alerta', kind: 'number', min: 3, max: 100 }, { key: 'windowSeconds', label: 'Janela de tempo (segundos)', kind: 'number', min: 5, max: 300 }, { key: 'incidentMinutes', label: 'Duração da proteção (minutos)', kind: 'number', min: 1, max: 120 }] }, { title: 'Resposta e recuperação', description: 'Escolhe o nível de verificação e onde a equipa é avisada.', fields: [{ key: 'verification', label: 'Nível de verificação', kind: 'select', options: [['medium', 'Médio'], ['high', 'Alto'], ['very_high', 'Muito alto']] }, { key: 'pauseInvites', label: 'Pausar convites durante o incidente', kind: 'toggle' }, { key: 'alertOnly', label: 'Apenas alertar', kind: 'toggle', advanced: true }, { key: 'alertChannel', label: 'Canal de alerta', kind: 'text', advanced: true }] }],
    'protection.join_gate': [{ title: 'Entrada segura', description: 'Filtra contas novas antes de lhes dar acesso completo.', fields: [{ key: 'minimumAccountDays', label: 'Idade mínima da conta (dias)', kind: 'number', min: 0, max: 365 }, { key: 'requireAvatar', label: 'Exigir avatar', kind: 'toggle' }, { key: 'action', label: 'Ação para contas suspeitas', kind: 'select', options: [['quarantine', 'Quarentena'], ['kick', 'Expulsar'], ['alert', 'Apenas alertar']] }] }, { title: 'Cargos e registo', description: 'Liga a verificação ao fluxo da tua comunidade.', fields: [{ key: 'verifiedRole', label: 'Cargo verificado', kind: 'text' }, { key: 'autoRole', label: 'Cargo inicial', kind: 'text' }, { key: 'blockedNamePatterns', label: 'Padrões de nome bloqueados', kind: 'tags', advanced: true }, { key: 'logChannel', label: 'Canal de registo', kind: 'text', advanced: true }] }],
    'community.levels': [{ title: 'Progressão', description: 'Cria um ritmo justo para membros ativos.', fields: [{ key: 'xpMin', label: 'XP mínimo por mensagem', kind: 'number', min: 1, max: 1000 }, { key: 'xpMax', label: 'XP máximo por mensagem', kind: 'number', min: 1, max: 2000 }, { key: 'cooldownSeconds', label: 'Cooldown entre mensagens (segundos)', kind: 'number', min: 0, max: 3600 }, { key: 'stackRoles', label: 'Acumular cargos de nível', kind: 'toggle' }] }, { title: 'Mensagens e recompensas', description: 'Personaliza o anúncio e os cargos sem editar comandos.', fields: [{ key: 'announceChannel', label: 'Canal de anúncio', kind: 'text' }, { key: 'announceTemplate', label: 'Mensagem de subida de nível', kind: 'textarea', help: 'Variáveis: {member}, {level}, {server}.', advanced: true }, { key: 'ignoredChannels', label: 'Canais sem XP', kind: 'tags', advanced: true }, { key: 'levelRoles', label: 'Recompensas por nível', kind: 'tags', advanced: true }] }],
    'community.starboard': [{ title: 'Destaques', description: 'Escolhe quando uma mensagem merece aparecer no canal especial.', fields: [{ key: 'emoji', label: 'Emoji de destaque', kind: 'text' }, { key: 'threshold', label: 'Reações necessárias', kind: 'number', min: 1, max: 100 }, { key: 'channel', label: 'Canal starboard', kind: 'text' }] }, { title: 'Regras da comunidade', description: 'Mantém o destaque relevante e seguro.', fields: [{ key: 'allowSelfStar', label: 'Permitir reação do autor', kind: 'toggle', advanced: true }, { key: 'includeImages', label: 'Incluir imagens', kind: 'toggle', advanced: true }, { key: 'ignoredChannels', label: 'Canais ignorados', kind: 'tags', advanced: true }] }],
    'community.suggestions': [{ title: 'Caixa de ideias', description: 'Define como os membros enviam e votam nas sugestões.', fields: [{ key: 'channel', label: 'Canal de sugestões', kind: 'text' }, { key: 'voteMode', label: 'Modo de votação', kind: 'select', options: [['up_down', 'Apoiar / não apoiar'], ['up_only', 'Apenas apoiar'], ['poll', 'Enquete']] }, { key: 'anonymous', label: 'Permitir sugestões anónimas', kind: 'toggle' }] }, { title: 'Moderação', description: 'Dá à equipa contexto e controlo sobre o fluxo.', fields: [{ key: 'cooldownHours', label: 'Cooldown por membro (horas)', kind: 'number', min: 0, max: 720, advanced: true }, { key: 'requiredRole', label: 'Cargo necessário', kind: 'text', advanced: true }, { key: 'staffChannel', label: 'Canal privado da equipa', kind: 'text', advanced: true }] }],
    'community.giveaways': [{ title: 'Valores predefinidos', description: 'Acelera a criação de sorteios no Discord.', fields: [{ key: 'defaultDurationHours', label: 'Duração predefinida (horas)', kind: 'number', min: 1, max: 720 }, { key: 'defaultWinners', label: 'Vencedores predefinidos', kind: 'number', min: 1, max: 50 }, { key: 'requiredRole', label: 'Cargo necessário', kind: 'text' }] }, { title: 'Proteções', description: 'Evita que o sorteio fique sem acompanhamento.', fields: [{ key: 'bonusRole', label: 'Cargo com entrada extra', kind: 'text', advanced: true }, { key: 'rerollHours', label: 'Prazo para reroll (horas)', kind: 'number', min: 1, max: 720, advanced: true }] }],
    'support.tickets': [{ title: 'Atendimento', description: 'Prepara o espaço para a equipa responder aos membros.', fields: [{ key: 'category', label: 'Categoria dos tickets', kind: 'text' }, { key: 'staffRoles', label: 'Cargos da equipa', kind: 'tags' }, { key: 'transcriptChannel', label: 'Canal de transcrições', kind: 'text' }, { key: 'maxOpen', label: 'Tickets abertos por membro', kind: 'number', min: 1, max: 10 }] }, { title: 'Painel de abertura', description: 'A primeira mensagem deve explicar claramente o próximo passo.', fields: [{ key: 'panelTitle', label: 'Título do painel', kind: 'text' }, { key: 'panelDescription', label: 'Descrição do painel', kind: 'textarea' }, { key: 'closeAfterHours', label: 'Fechar por inatividade (horas)', kind: 'number', min: 0, max: 8760, advanced: true }] }],
    'support.welcome': [{ title: 'Mensagem de entrada', description: 'Dá boas-vindas sem obrigar a editar código.', fields: [{ key: 'channel', label: 'Canal público', kind: 'text' }, { key: 'message', label: 'Mensagem pública', kind: 'textarea', help: 'Variáveis: {member}, {server}, {count}.' }, { key: 'delaySeconds', label: 'Atraso (segundos)', kind: 'number', min: 0, max: 3600 }] }, { title: 'Mensagem privada e cargo', description: 'Completa o onboarding para novos membros.', fields: [{ key: 'sendDm', label: 'Enviar mensagem privada', kind: 'toggle' }, { key: 'dmMessage', label: 'Mensagem privada', kind: 'textarea', advanced: true }, { key: 'autoRole', label: 'Cargo inicial', kind: 'text', advanced: true }] }],
    'management.nickname': [{ title: 'Nome no servidor', description: 'Escolhe como o Helper aparece na lista de membros deste servidor.', fields: [{ key: 'nickname', label: 'Nickname do Helper', kind: 'text', maxLength: 32, help: 'Até 32 caracteres. Deixa vazio para remover o nome personalizado.' }] }],
    'management.workflows': [{ title: 'Predefinições', description: 'Os fluxos completos podem ser adicionados depois desta base segura.', fields: [{ key: 'defaultAction', label: 'Ação predefinida', kind: 'select', options: [['send_message', 'Enviar mensagem'], ['add_role', 'Adicionar cargo'], ['remove_role', 'Remover cargo']] }, { key: 'logChannel', label: 'Canal de execução', kind: 'text' }] }, { title: 'Segurança', description: 'Testa primeiro e publica só quando estiveres confiante.', fields: [{ key: 'dryRun', label: 'Abrir novos fluxos em modo de teste', kind: 'toggle' }, { key: 'workflows', label: 'Fluxos guardados', kind: 'tags', advanced: true }] }],
    'management.polls': [{ title: 'Votações', description: 'Define defaults para enquetes rápidas.', fields: [{ key: 'channel', label: 'Canal predefinido', kind: 'text' }, { key: 'defaultDurationHours', label: 'Duração predefinida (horas)', kind: 'number', min: 1, max: 720 }, { key: 'allowMultiple', label: 'Permitir várias escolhas', kind: 'toggle' }] }, { title: 'Privacidade e lembretes', description: 'Controla a exposição dos votos.', fields: [{ key: 'anonymous', label: 'Votos anónimos', kind: 'toggle', advanced: true }, { key: 'reminderHours', label: 'Lembrete antes de fechar (horas)', kind: 'number', min: 0, max: 168, advanced: true }] }],
    'insights.stats': [{ title: 'Canais de estatísticas', description: 'Mostra os dados importantes sem poluir o servidor.', fields: [{ key: 'channel', label: 'Canal de estatísticas', kind: 'text' }, { key: 'refreshMinutes', label: 'Atualização (minutos)', kind: 'number', min: 5, max: 1440 }, { key: 'showMembers', label: 'Mostrar membros', kind: 'toggle' }, { key: 'showMessages', label: 'Mostrar mensagens', kind: 'toggle' }, { key: 'showVoice', label: 'Mostrar atividade de voz', kind: 'toggle' }] }],
  };
  return map[key] ?? [{ title: 'Configuração', description: 'Ajusta esta funcionalidade ao teu servidor.', fields: [{ key: 'notes', label: 'Notas da equipa', kind: 'textarea' }, { key: 'alertOnly', label: 'Apenas alertar', kind: 'toggle' }] }];
};

function parseRoute(hash: string): Route { const value = hash.replace(/^#/, '') || '/'; if (value === '/' || value === '') return { page: 'overview' }; if (value === '/features' || value === '/config') return { page: 'features' }; if (value === '/activity') return { page: 'activity' }; if (value === '/rank-card') return { page: 'rank-card' }; if (value.startsWith('/config/')) return { page: 'detail', key: decodeURIComponent(value.slice('/config/'.length)) }; return { page: 'overview' }; }

function App() {
  const [route, setRoute] = useState<Route>(() => parseRoute(window.location.hash));
  const [me, setMe] = useState<Me | null>(null); const [guilds, setGuilds] = useState<Guild[]>(demoGuilds); const [features, setFeatures] = useState<Feature[]>(demoFeatures); const [cases, setCases] = useState<CaseRecord[]>([]); const [audit, setAudit] = useState<AuditRecord[]>([]); const [stats, setStats] = useState({ totalCases: 0 }); const [quota, setQuota] = useState({ plan: 'Free', limits: {} as Record<string, number>, usage: {} as Record<string, number> });
  const [rankConfig, setRankConfig] = useState(defaultRankCard); const [savedRankConfig, setSavedRankConfig] = useState(defaultRankCard); const [detailConfig, setDetailConfig] = useState<FeatureConfig>({}); const [savedDetailConfig, setSavedDetailConfig] = useState<FeatureConfig>({}); const [detailEnabled, setDetailEnabled] = useState(false); const [status, setStatus] = useState<'loading' | 'ready' | 'error' | 'auth' | 'saving'>('loading'); const [message, setMessage] = useState(''); const [authError, setAuthError] = useState(''); const [authLoading, setAuthLoading] = useState(false); const [search, setSearch] = useState(''); const [filter, setFilter] = useState<Category>('all'); const [detailLoading, setDetailLoading] = useState(false);

  const navigate = (path: string) => { const next = parseRoute(path); if (window.location.hash === path) setRoute(next); else window.location.hash = path; };
  useEffect(() => { const onHash = () => setRoute(parseRoute(window.location.hash)); window.addEventListener('hashchange', onHash); if (!window.location.hash) window.location.hash = '#/'; return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => {
    if (localPreviewMode) { setMe({ id: 'demo', guildId: 'demo', expiresAt: new Date(Date.now() + 86_400_000).toISOString(), dbOk: true }); setStatus('ready'); return; }
    void Promise.all([api.me(), api.guilds().catch(() => ({ guilds: demoGuilds })), api.features().catch(() => ({ guildId: '', features: demoFeatures })), api.stats().catch(() => ({ totalCases: 0, guildId: '' })), api.cases().catch(() => ({ cases: [] })), api.audit().catch(() => ({ events: [] })), api.quotas().catch(() => ({ plan: 'Free', limits: {}, usage: {} })), api.rankCard().catch(() => ({ guildId: '', config: defaultRankCard }))]).then(([nextMe, nextGuilds, nextFeatures, nextStats, nextCases, nextAudit, nextQuota, nextRank]) => { setMe(nextMe); setGuilds(nextGuilds.guilds); setFeatures(nextFeatures.features); setStats(nextStats); setCases(nextCases.cases); setAudit(nextAudit.events); setQuota(nextQuota); setRankConfig(nextRank.config); setSavedRankConfig(nextRank.config); setStatus('ready'); }).catch((cause: unknown) => { setMessage(cause instanceof Error ? cause.message : 'Não foi possível carregar o painel.'); setStatus('error'); });
   }, []);
   async function startLogin() { setAuthLoading(true); setAuthError(''); try { await api.startOAuth(); } catch (cause) { setAuthError(cause instanceof Error ? cause.message : 'Não foi possível iniciar o acesso com Discord.'); setAuthLoading(false); } }
  useEffect(() => {
    if (route.page !== 'detail' || !route.key) return;
    setDetailLoading(true); const fallback = defaults[route.key] ?? {};
    if (localPreviewMode) { setDetailConfig({ ...fallback }); setSavedDetailConfig({ ...fallback }); setDetailEnabled(features.find((item) => item.key === route.key)?.enabled ?? false); setDetailLoading(false); return; }
    void api.feature(route.key).then((result) => { setDetailConfig({ ...fallback, ...result.config }); setSavedDetailConfig({ ...fallback, ...result.config }); setDetailEnabled(result.enabled); }).catch(() => { setDetailConfig({ ...fallback }); setSavedDetailConfig({ ...fallback }); setDetailEnabled(features.find((item) => item.key === route.key)?.enabled ?? false); }).finally(() => setDetailLoading(false));
  }, [route.page, route.key, features]);

  const currentGuild = guilds.find((guild) => guild.id === me?.guildId) ?? guilds[0]; const currentFeature = features.find((item) => item.key === route.key); const detailDirty = JSON.stringify(detailConfig) !== JSON.stringify(savedDetailConfig); const rankDirty = JSON.stringify(rankConfig) !== JSON.stringify(savedRankConfig); const dirty = route.page === 'detail' ? detailDirty : route.page === 'rank-card' ? rankDirty : false;
  const filteredFeatures = useMemo(() => { const unique = Array.from(new Map(features.map((item) => [item.key, item])).values()); return unique.filter((item) => (filter === 'all' || item.category === filter) && item.label.toLocaleLowerCase().includes(search.toLocaleLowerCase())); }, [features, filter, search]);
  async function switchGuild(guildId: string) { if (localPreviewMode) { setMe((current) => current ? { ...current, guildId } : current); return; } try { await api.switchGuild(guildId); window.location.reload(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Não foi possível trocar de servidor.'); } }
  async function saveDetail() { if (!route.key) return; setStatus('saving'); try { const result = localPreviewMode ? { enabled: detailEnabled, config: detailConfig } : await api.saveFeature(route.key, detailEnabled, detailConfig); setFeatures((items) => items.map((item) => item.key === route.key ? { ...item, enabled: result.enabled } : item)); setDetailConfig(result.config); setSavedDetailConfig(result.config); setStatus('ready'); setMessage(localPreviewMode ? 'Pré-visualização guardada neste navegador.' : 'Configuração publicada no servidor.'); } catch (cause) { setStatus('error'); setMessage(cause instanceof Error ? cause.message : 'Não foi possível guardar.'); } }
  async function testDetail() { if (!route.key) return; try { await api.testFeature(route.key, detailConfig); setMessage('Simulação concluída — nenhuma ação real foi aplicada.'); } catch { setMessage('A simulação está disponível quando a API estiver ligada.'); } }
  async function saveRankCard() { setStatus('saving'); try { const result = localPreviewMode ? { config: rankConfig } : await api.saveRankCard(rankConfig); setRankConfig(result.config); setSavedRankConfig(result.config); setStatus('ready'); setMessage(localPreviewMode ? 'Pré-visualização guardada neste navegador.' : 'XP card publicado no servidor.'); } catch (cause) { setStatus('error'); setMessage(cause instanceof Error ? cause.message : 'Não foi possível publicar.'); } }
  if (status === 'loading') return <div className="center"><div className="loader" /><p>A preparar o teu espaço de trabalho…</p></div>;
  if ((status === 'auth' || status === 'error') && !me) return <AuthScreen error={status === 'auth' ? authError : message} loading={authLoading} onLogin={() => void startLogin()} />;
  const title = route.page === 'detail' ? currentFeature?.label ?? 'Configuração' : pages.find((item) => item.id === route.page)?.label;
  const subtitle = route.page === 'overview' ? 'O essencial para deixares o servidor pronto.' : route.page === 'features' ? 'Escolhe um tópico para abrir a configuração completa.' : route.page === 'activity' ? 'Vê o que aconteceu e mantém o controlo.' : route.page === 'rank-card' ? 'Cria uma carta de nível com a identidade do teu servidor.' : 'Configuração por servidor, com opções simples e avançadas.';
  return <div className="shell"><aside className="sidebar"><div className="logo"><span>✦</span><div><strong>VOZEN</strong><small>HELPER PANEL</small></div></div><div className="workspace"><small>SERVIDOR ATUAL</small><select value={currentGuild?.id ?? ''} onChange={(event) => void switchGuild(event.target.value)}>{guilds.map((guild) => <option value={guild.id} key={guild.id}>{guild.name}</option>)}</select><p>As alterações ficam isoladas neste servidor.</p></div><nav aria-label="Navegação principal">{pages.map((item) => <button key={item.id} className={route.page === item.id || (item.id === 'features' && route.page === 'detail') ? 'nav active' : 'nav'} onClick={() => navigate(item.id === 'overview' ? '#/' : `#/${item.id}`)}><span>{item.icon}</span><div><b>{item.label}</b><small>{item.hint}</small></div></button>)}</nav><div className="runtime"><i /> {localPreviewMode ? 'Pré-visualização local' : 'Sincronizado com Rust'}</div></aside><main className="main"><header><div><small className="eyebrow">{currentGuild?.name ?? 'WORKSPACE'} · HELPER</small><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><div className="header-state"><span className="status-dot" /> {dirty ? 'Rascunho por publicar' : localPreviewMode ? 'Modo de demonstração' : 'Tudo sincronizado'}</div></header>{message && <div className="toast" role="status">{message}<button aria-label="Fechar" onClick={() => setMessage('')}>×</button></div>}{route.page === 'overview' && <Overview features={features} stats={stats} quota={quota} cases={cases} onOpen={navigate} />}{route.page === 'features' && <FeatureCatalogue features={filteredFeatures} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} onOpen={(key) => navigate(key === 'studio.rank_card' ? '#/rank-card' : `#/config/${encodeURIComponent(key)}`)} />}{route.page === 'activity' && <Activity cases={cases} audit={audit} />}{route.page === 'rank-card' && <RankCardEditor config={rankConfig} patch={(next) => setRankConfig((current) => ({ ...current, ...next }))} onSave={() => void saveRankCard()} onReset={() => setRankConfig(defaultRankCard)} saving={status === 'saving'} />}{route.page === 'detail' && (detailLoading ? <div className="loading-card card"><div className="loader" /><span>A carregar configuração…</span></div> : <FeatureDetail feature={currentFeature} config={detailConfig} enabled={detailEnabled} onEnabled={setDetailEnabled} onChange={(key, value) => setDetailConfig((current) => ({ ...current, [key]: value }))} onSave={() => void saveDetail()} onDiscard={() => { setDetailConfig(savedDetailConfig); setDetailEnabled(features.find((item) => item.key === route.key)?.enabled ?? false); }} onTest={() => void testDetail()} saving={status === 'saving'} onBack={() => navigate('#/features')} />)}</main></div>;
}

function AuthScreen({ error, loading, onLogin }: { error: string; loading: boolean; onLogin: () => void }) { const visibleError = /unauthenticated|API 401/i.test(error) ? '' : error; return <main className="auth-shell"><div className="auth-brand"><span>✦</span><div><strong>VOZEN</strong><small>HELPER PANEL</small></div></div><section className="auth-card card"><div className="auth-icon">✦</div><small className="eyebrow">ACESSO SEGURO</small><h1>Entra no teu painel</h1><p>Usa a tua conta Discord para gerir o Helper e configurar os teus servidores.</p><button className="primary auth-button" onClick={onLogin} disabled={loading}>{loading ? 'A ligar ao Discord…' : 'Continuar com Discord'}</button>{visibleError && <p className="auth-error" role="alert">{visibleError}</p>}<small className="auth-note">O acesso é protegido e só mostra servidores onde tens permissão de gestão.</small></section></main>; }

function Overview({ features, stats, quota, cases, onOpen }: { features: Feature[]; stats: { totalCases: number }; quota: { plan: string; limits: Record<string, number>; usage: Record<string, number> }; cases: CaseRecord[]; onOpen: (path: string) => void }) { const enabled = features.filter((feature) => feature.enabled).length; return <><section className="welcome card"><div><small className="eyebrow">CENTRO DE COMANDO</small><h2>O teu servidor, sob controlo.</h2><p>Vê o que precisa de atenção e configura o Helper por etapas simples. Cada alteração fica ligada ao teu servidor.</p><button className="primary" onClick={() => onOpen('#/features')}>Configurar o Helper</button></div><div className="setup-steps"><button onClick={() => onOpen('#/config/protection.antispam')}><span>1</span><div><b>Proteger o servidor</b><small>{enabled} funcionalidades ativas</small></div><em>›</em></button><button onClick={() => onOpen('#/config/support.welcome')}><span>2</span><div><b>Receber novos membros</b><small>Mensagem e cargo inicial</small></div><em>›</em></button><button onClick={() => onOpen('#/config/community.levels')}><span>3</span><div><b>Dar vida à comunidade</b><small>Níveis, XP e recompensas</small></div><em>›</em></button></div></section><div className="metrics"><Metric value={String(enabled)} label="funcionalidades ativas" /><Metric value={String(stats.totalCases)} label="casos de moderação" /><Metric value={String(cases.length)} label="eventos recentes" /><Metric value={quota.plan} label="plano atual" /></div><section className="section-heading"><div><small className="eyebrow">RECOMENDADO</small><h2>O que queres fazer primeiro?</h2></div><button className="link-button" onClick={() => onOpen('#/features')}>Ver tudo →</button></section><div className="quick-grid"><Quick icon="🛡" title="Proteger o servidor" text="Anti-spam, anti-raid e proteção de entradas." onClick={() => onOpen('#/config/protection.antispam')} /><Quick icon="✦" title="Dar vida à comunidade" text="Níveis, sugestões, sorteios e starboard." onClick={() => onOpen('#/config/community.levels')} /><Quick icon="▣" title="Criar identidade" text="Escolhe cores, tipografia e um banner seguro." onClick={() => onOpen('#/rank-card')} /></div><section className="quota card"><div><small className="eyebrow">LIMITE DO PLANO</small><h3>Usa o Helper com espaço para crescer</h3><p>O plano atual mostra os limites antes de uma ação ficar bloqueada.</p></div><div className="quota-items"><Quota label="Workflows" used={quota.usage.workflows ?? 0} limit={quota.limits.workflows ?? 0} /><Quota label="Templates" used={quota.usage.templates ?? 0} limit={quota.limits.templates ?? 0} /><Quota label="Role panels" used={quota.usage.role_panels ?? 0} limit={quota.limits.role_panels ?? 0} /></div></section></>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="metric card"><strong>{value}</strong><span>{label}</span></div>; }
function Quota({ label, used, limit }: { label: string; used: number; limit: number }) { const percent = limit > 0 ? Math.min(100, Math.round((used / limit) * 100)) : 0; return <div className="quota-item"><div><span>{label}</span><b>{used} / {limit || '—'}</b></div><i><em style={{ width: `${percent}%` }} /></i></div>; }
function Quick({ icon, title, text, onClick }: { icon: string; title: string; text: string; onClick: () => void }) { return <button className="quick card" onClick={onClick}><span className="quick-icon">{icon}</span><div><h3>{title}</h3><p>{text}</p></div><b>→</b></button>; }

function FeatureCatalogue({ features, filter, setFilter, search, setSearch, onOpen }: { features: Feature[]; filter: Category; setFilter: (value: Category) => void; search: string; setSearch: (value: string) => void; onOpen: (key: string) => void }) { return <section><div className="catalog-toolbar"><div><small className="eyebrow">CATÁLOGO DO HELPER</small><h2>Escolhe o que o teu servidor precisa</h2><p>Abre um tópico para veres opções essenciais, definições avançadas e uma simulação segura.</p></div><input className="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Pesquisar funcionalidade…" aria-label="Pesquisar funcionalidade" /></div><div className="filters">{categories.map((category) => <button key={category.id} className={filter === category.id ? 'filter active' : 'filter'} onClick={() => setFilter(category.id)}>{category.label}</button>)}</div><div className="feature-grid">{features.map((feature) => <article className="feature card" key={feature.key}><div className="feature-top"><span className={`feature-icon ${feature.category}`}>{feature.category === 'protection' ? '◈' : feature.category === 'community' ? '✦' : '▤'}</span><span className={feature.available ? feature.enabled ? 'pill on' : 'pill' : 'pill muted'}>{feature.available ? feature.enabled ? 'Ativa' : 'Disponível' : 'Em breve'}</span></div><h3>{feature.label}</h3><p>{feature.description}</p><button className="secondary full" disabled={!feature.available} onClick={() => onOpen(feature.key)}>{feature.key === 'studio.rank_card' ? 'Personalizar' : 'Configurar'}</button></article>)}</div>{!features.length && <div className="empty card">Não encontrámos funcionalidades com esse filtro.</div>}</section>; }

function FeatureDetail({ feature, config, enabled, onEnabled, onChange, onSave, onDiscard, onTest, saving, onBack }: { feature?: Feature; config: FeatureConfig; enabled: boolean; onEnabled: (value: boolean) => void; onChange: (key: string, value: unknown) => void; onSave: () => void; onDiscard: () => void; onTest: () => void; saving: boolean; onBack: () => void }) { const sections = spec(feature?.key ?? ''); return <section className="detail-page"><button className="back-link" onClick={onBack}>← Voltar às funcionalidades</button><div className="detail-intro card"><div><small className="eyebrow">CONFIGURAÇÃO · {feature?.category === 'protection' ? 'PROTEÇÃO' : feature?.category === 'community' ? 'COMUNIDADE' : 'GESTÃO'}</small><h2>{feature?.label ?? 'Funcionalidade'}</h2><p>{feature?.description ?? 'Ajusta esta funcionalidade ao teu servidor.'}</p></div><label className="switch-row"><span><b>{enabled ? 'Ativa' : 'Desativada'}</b><small>O Helper aplica esta configuração no servidor.</small></span><input type="checkbox" checked={enabled} onChange={(event) => onEnabled(event.target.checked)} /></label></div><div className="detail-layout"><div className="detail-sections">{sections.map((section) => <ConfigSection key={section.title} section={section} config={config} onChange={onChange} />)}</div><aside className="detail-aside card"><div><small className="eyebrow">ANTES DE PUBLICAR</small><h3>Confere sem risco</h3><p>Usa a simulação para veres o que aconteceria. Ela nunca apaga mensagens nem castiga membros.</p></div><button className="secondary full" onClick={onTest}>Simular configuração</button><div className="tip"><b>Precisas de ajuda?</b><span>Os campos avançados estão fechados para manter o primeiro passo simples.</span></div></aside></div><div className="sticky-actions"><button className="secondary" onClick={onDiscard} disabled={saving}>Descartar</button><button className="primary" onClick={onSave} disabled={saving}>{saving ? 'A guardar…' : 'Guardar alterações'}</button></div></section>; }
function ConfigSection({ section, config, onChange }: { section: SectionSpec; config: FeatureConfig; onChange: (key: string, value: unknown) => void }) { const advanced = section.fields.filter((field) => field.advanced); const basic = section.fields.filter((field) => !field.advanced); return <section className="config-section card"><div className="section-heading"><div><small className="eyebrow">CONFIGURAÇÃO</small><h3>{section.title}</h3><p>{section.description}</p></div></div><div className="field-grid">{basic.map((field) => <FieldControl field={field} key={field.key} value={config[field.key]} onChange={onChange} />)}</div>{advanced.length > 0 && <details className="advanced"><summary>Opções avançadas <span>{advanced.length} definições</span></summary><div className="field-grid">{advanced.map((field) => <FieldControl field={field} key={field.key} value={config[field.key]} onChange={onChange} />)}</div></details>}</section>; }
function FieldControl({ field, value, onChange }: { field: FieldSpec; value: unknown; onChange: (key: string, value: unknown) => void }) { const normalized = value ?? (field.kind === 'toggle' ? false : field.kind === 'tags' ? [] : ''); if (field.kind === 'toggle') return <label className="field toggle-field"><span><b>{field.label}</b>{field.help && <small>{field.help}</small>}</span><input type="checkbox" checked={Boolean(normalized)} onChange={(event) => onChange(field.key, event.target.checked)} /></label>; if (field.kind === 'textarea') return <label className="field"><span><b>{field.label}</b>{field.help && <small>{field.help}</small>}</span><textarea value={String(normalized)} onChange={(event) => onChange(field.key, event.target.value)} rows={3} /></label>; if (field.kind === 'tags') return <label className="field"><span><b>{field.label}</b><small>{field.help ?? 'Separa vários valores por vírgulas.'}</small></span><input value={Array.isArray(normalized) ? normalized.join(', ') : String(normalized)} onChange={(event) => onChange(field.key, event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} /></label>; if (field.kind === 'select') return <label className="field"><span><b>{field.label}</b>{field.help && <small>{field.help}</small>}</span><select value={String(normalized)} onChange={(event) => onChange(field.key, event.target.value)}>{field.options?.map(([option, label]) => <option value={option} key={option}>{label}</option>)}</select></label>; return <label className="field"><span><b>{field.label}</b>{field.help && <small>{field.help}</small>}</span><input type={field.kind} min={field.min} max={field.max} maxLength={field.maxLength} step={field.step ?? 1} value={field.kind === 'number' ? Number(normalized) : String(normalized)} onChange={(event) => onChange(field.key, field.kind === 'number' ? Number(event.target.value) : event.target.value)} /></label>; }

function Activity({ cases, audit }: { cases: CaseRecord[]; audit: AuditRecord[] }) { return <section className="activity"><div className="section-heading"><div><small className="eyebrow">TRANSPARÊNCIA</small><h2>Atividade recente</h2><p>Cada ação mostra o que aconteceu sem esconder detalhes importantes.</p></div></div><div className="table card"><div className="table-head"><span>Ação</span><span>Alvo / ator</span><span>Estado</span><span>Data</span></div>{cases.map((item) => <div className="table-row" key={`case-${item.id}`}><span><b className="tag danger">{item.kind ?? item.type ?? 'moderação'}</b></span><span>{item.target_id ?? item.targetId ?? '—'}</span><span>{item.reason || 'Sem motivo indicado'}</span><span>{formatDate(item.created_at ?? item.createdAt)}</span></div>)}{audit.map((item, index) => <div className="table-row" key={`audit-${index}`}><span><b className="tag">{item.action}</b></span><span>{item.actor_id ?? item.actorId ?? '—'}</span><span>{item.outcome}</span><span>{formatDate(item.created_at)}</span></div>)}{!cases.length && !audit.length && <div className="empty">Ainda não há atividade para mostrar.</div>}</div></section>; }
function formatDate(value?: number | string) { if (!value) return '—'; const date = typeof value === 'number' ? new Date(value < 2_000_000_000 ? value * 1000 : value) : new Date(value); return Number.isNaN(date.valueOf()) ? '—' : date.toLocaleString('pt-PT', { dateStyle: 'short', timeStyle: 'short' }); }

function RankCardEditor({ config, patch, onSave, onReset, saving }: { config: RankCardConfig; patch: (next: Partial<RankCardConfig>) => void; onSave: () => void; onReset: () => void; saving: boolean }) { return <section className="editor-grid"><div className="card preview-panel"><div className="card-title"><div><small className="eyebrow">PRÉ-VISUALIZAÇÃO AO VIVO</small><h2>Assim aparece no Discord</h2></div><span className="live-dot">● ao vivo</span></div><RankPreview config={config} /></div><div className="card controls"><div className="card-title"><div><small className="eyebrow">EDITOR SEGURO</small><h2>Identidade do XP card</h2><p>Usa apenas banners curados pelo Vozen ou uma cor sólida.</p></div></div><label>Fonte<select value={config.font} onChange={(event) => patch({ font: event.target.value })}><option value="system">System</option><option value="inter">Inter</option><option value="roboto">Roboto</option><option value="poppins">Poppins</option><option value="space_grotesk">Space Grotesk</option><option value="lexend">Lexend</option></select></label><ColorField label="Cor principal" value={config.primary_color} swatches={swatches} onChange={(value) => patch({ primary_color: value, avatar_ring_color: value })} /><ColorField label="Cor do texto" value={config.text_color} swatches={swatches} onChange={(value) => patch({ text_color: value })} /><label>Opacidade do overlay <output>{Math.round(config.overlay_opacity * 100)}%</output><input type="range" min="0" max="0.85" step="0.01" value={config.overlay_opacity} onChange={(event) => patch({ overlay_opacity: Number(event.target.value) })} /></label><BackgroundPicker config={config} patch={patch} /><div className="actions"><button className="secondary" onClick={onReset}>Restaurar</button><button className="primary" onClick={onSave} disabled={saving}>{saving ? 'A guardar…' : 'Guardar alterações'}</button></div></div></section>; }
function BackgroundPicker({ config, patch }: { config: RankCardConfig; patch: (next: Partial<RankCardConfig>) => void }) { const preset = config.background_preset; return <div className="background-picker"><div className="field-label"><span>Fundo do XP card</span><small>{preset ? 'Banner curado' : 'Cor sólida'}</small></div><div className="background-modes"><button type="button" className={!preset ? 'mode selected' : 'mode'} onClick={() => patch({ background_preset: null, background_url: null, background_data: null })}>Cor sólida</button><button type="button" className={preset ? 'mode selected' : 'mode'} onClick={() => patch({ background_preset: preset ?? presetOptions[0][0], background_url: null, background_data: null })}>Banners</button></div>{preset ? <div className="banner-grid">{presetOptions.map(([id, label, path]) => <button type="button" className={preset === id ? 'banner-option selected' : 'banner-option'} key={id} onClick={() => patch({ background_preset: id, background_url: null, background_data: null })}><img src={path} alt="" /><span>{label}</span></button>)}</div> : <ColorField label="Escolhe uma cor de fundo" value={config.background_color} swatches={['#101725', '#172033', '#1F2937', '#312E46', '#3B2434', '#243A36']} onChange={(value) => patch({ background_color: value })} />}</div>; }
function ColorField({ label, value, swatches: colors, onChange }: { label: string; value: string; swatches: string[]; onChange: (value: string) => void }) { return <div className="color-field"><div className="field-label"><span>{label}</span><input type="color" value={value} onChange={(event) => onChange(event.target.value.toUpperCase())} /></div><div className="swatches">{colors.map((color) => <button type="button" aria-label={color} key={color} className={color.toLowerCase() === value.toLowerCase() ? 'swatch selected' : 'swatch'} style={{ background: color }} onClick={() => onChange(color)} />)}</div></div>; }
function RankPreview({ config }: { config: RankCardConfig }) { const background = presetOptions.find(([id]) => id === config.background_preset)?.[2]; const backgroundImage = background ? `linear-gradient(rgba(0,0,0,${config.overlay_opacity}), rgba(0,0,0,${config.overlay_opacity})), url(${JSON.stringify(background)})` : undefined; return <div className="rank-preview" style={{ backgroundColor: config.background_color, backgroundImage, fontFamily: config.font === 'system' ? 'system-ui' : config.font.replace('_', ' ') }}><div className="rank-avatar" style={{ borderColor: config.avatar_ring_color, borderWidth: config.avatar_ring_width }}><span>✦</span></div><div className="rank-content"><div className="rank-top"><strong style={{ color: config.text_color }}>Lunara</strong><div><b style={{ color: config.primary_color }}>Rank #17</b><b style={{ color: config.text_color }}>Level 8</b></div></div><p style={{ color: config.primary_color }}>lunara#4821</p><div className="xp-meta"><span style={{ color: config.text_color }}>429 / 1337 XP</span><span style={{ color: config.text_color }}>32%</span></div><div className="xp-track"><i style={{ background: config.primary_color, width: '32%' }} /></div></div></div>; }

export default App;
